### ISSUE TITLE
Suggestion: Push REXP Stored, Usable This Cycle and Cycle Refreshes Info to Experience Window

### ISSUE THREAD

**Issue by dantiadr** [GenieClient/Genie4#10]
Would like to have the option to push this info to the Experience window so I don't have to keep checking EXP.

**Comment by dantiadr** [comment]
Would like to have the option to push this info to the Experience window so I don't have to keep checking EXP.

**Comment by jingounchained** [comment]
this would fall in the domain of EXPTracker - https://github.com/vtcifer/g3-standalone-xp
There has been mention of possibly internalizing it but for now no decision has been to do so that I'm aware of
Going to close this one out. Will revisit if we do internalize EXPTracker
