### ISSUE TITLE
When using condensed mode, odd spacing present in Game window display for room description, object lists, and obvious paths/exits

### ISSUE THREAD

**Issue by Altaire-81** [GenieClient/Genie4#103]
When running Genie 4.0.2.4 in condensed mode (#config condensed True), the following can be observed:

1) If there are objects in the room (i.e., "You also see <list here>") then there's no whitespace between the end of the room description and the beginning of the objects/NPCs list.  After that list terminates, you get a carriage return and the obvious paths/exits are on their own line.  This is actually not bad behavior in general, other than the fact that a space or two in between the end of the room desc. and the beginning of the objects list would be appreciated.

2) If there are no "you also see" objects in the room, the obvious paths/exits get appended, with no whitespace/carriage return, directly to the end of the room description.  I'm thinking that it'd be more readable with the exits/paths on their own line, even with 'condensed' active (IF that's a thing that's reasonably doable -- I thought I remembered you guys saying that there was some processing to 'catch' a few of these types of lines specifically.)

**Comment by jingounchained** [comment]
I agree. I will take a look.

**Comment by jingounchained** [comment]
Please give this a look in the latest Test Build
https://github.com/GenieClient/Genie4/releases/edit/Test_Build

**Comment by Altaire-81** [comment]
> Please give this a look in the latest Test Build https://github.com/GenieClient/Genie4/releases/edit/Test_Build

I checked it with condensed on and off just for laughs, and the room description comes through perfectly to the game window in all cases I've seen so far.  Really nice work!

(I did a quick run-around and it looks like the objects list and obvious paths are all working cleanly in .406.  I didn't check weird corner-case places yet, in case they'd work differently (ships, mazes, etc.) but a run around the Crossing, Knife Clan, some crafting societies and the NTR looked clean in places they definitely didn't under the previous few versions.)

**Comment by jingounchained** [comment]
Awesome! Yeah 406 has some other changes. I've been trying to get pushBold applying correctly to everything and that's the major focus of the current development thread. And as a bonus this is handled in the same area of code I was working so it fits nicely to include. I'll attach this to the PR once all other tests pass. Thank you for your help!
