### ISSUE TITLE
Inventory View plugin and #config showlinks

### ISSUE THREAD

**Issue by hat071af** [GenieClient/Genie4#106]
When selecting "Scan Inventory" from the default Inventory View plugin from the plugins zip file, it only outputs the INVENTORY LIST command if #config showlinks has been enabled. Normal behavior is that it would also check your vault, eddy and home.

Disabling showlinks does not resolve it, however reloading the Inventory View plugin once showlinks has been disabled does.

**Comment by Thires** [comment]
that is because of the plugin itself
                else if (ScanMode == "Inventory")
                {
                    if (text.StartsWith("[Use INVENTORY HELP"))
                    
it is looking for that and with showlinks it is [Use <d cmd='inventory help'>INVENTORY HELP</d> for more options.]

quick easy fix is just to have  if (text.StartsWith("[Use"))

not even sure that section is required

**Comment by mj-colonel-panic** [comment]
closing as this an InventoryView issue
