### ISSUE TITLE
#highlights command does not create path to sound file

### ISSUE THREAD

**Issue by GreyhallowDR** [GenieClient/Genie4#111]
Just tried adding some highlights via the command line which included a sound. It didn't assign the wav file, I had to go into the config menu and select the sound that way. Not a major issue but would be nice if sounds could be added from the command line.

#highlight {string} {Yellow} {pattern} {} {C:\Users\...\sound.wav}

**Comment by jingounchained** [comment]
Please try the latest test build at https://github.com/GenieClient/Genie4/releases/tag/Test_Build

I've expanded the #Highlight command to take all the parameters so you should be able to set a soundfile now
