### ISSUE TITLE
Having a space in the filepath for the configured editor breaks Script Editor functionality

### ISSUE THREAD

**Issue by valy1234** [GenieClient/Genie4#112]
For instance, anything with "Program Files" throws an error when attempting to create or edit a script.

**Comment by jingounchained** [comment]
I'm not having success in recreating this
My own editor setting is **editor=C:\Program Files\Notepad++\notepad++.exe**
Can you copy/paste your editor from #config?

**Comment by valy1234** [comment]
Hi, thanks for taking a look.

editor=C:\Program Files\Notepad++\notepad++.exe



*Orrin Cummins*
*オリン カミンス*

▌Japanese to English Translator
▌English Proofreader & Editor

▌Contact me to discuss the specifics of your project and find the
▌optimal solution to your Japanese to English translation needs.

***@***.***

**Comment by jingounchained** [comment]
3 things:
First, can you verify that NPP is actually installed at that location? 
Second, assuming it is installed, what is the error it throws?
Finally, can you try the latest Test Build at https://github.com/GenieClient/Genie4/releases/tag/Test_Build and see if that resolves the issue? I still can't recreate it having the exact same config

**Comment by valy1234** [comment]
I'll try the updated one soon and report back. Thanks again.

P.S. Shot in the dark, but could it have to do with running G4 as admin?
('m not currently)

*Orrin Cummins*
*オリン カミンス*

▌Japanese to English Translator
▌English Proofreader & Editor

▌Contact me to discuss the specifics of your project and find the
▌optimal solution to your Japanese to English translation needs.

***@***.***

**Comment by jingounchained** [comment]
I don't believe it would. I don't run as admin and I've been trying to get rid of anything that might require it (it was necessary for Lich for a while and shouldn't be any more) - but one possibility on that end is if your NPP install is locked behind admin privileges it could require you to be running that way to launch. Possibly. 

You can try checking the Security on your NPP Folder and making sure that Users have Read & Execute permission
![image](https://user-images.githubusercontent.com/32217493/187337229-5ba84b61-aad5-443b-9b0d-0f601a1145d1.png)

**Comment by valy1234** [comment]
Tried the newest test build:


[image: image.png]



This looked good, but it gave me an idea:

[image: image.png]


Turned this off (it was checked):

[image: image.png]


Now I can both create new scripts and edit existing ones (in Notepad++) via
the Script Explorer dialog box.

I've experienced a similar issue with a DAW where I couldn't drag-and-drop
audio files into it when running it as admin. I don't know how this stuff
works behind the scenes, but it feels like running a program as
administrator can prevent those without admin access from interacting with
them in certain ways.


At any rate, the issue seems resolved. Thank you very much for the
assistance!

*Orrin Cummins*
*オリン カミンス*

▌Japanese to English Translator
▌English Proofreader & Editor

▌Contact me to discuss the specifics of your project and find the
▌optimal solution to your Japanese to English translation needs.

***@***.***

**Comment by jingounchained** [comment]
Awesome! Running things with elevated permissions can get weird sometimes when something with less permission needs to interact, but I don't usually see that with the file system. At any rate I'm really glad it worked out!

**Comment by valy1234** [comment]
[image: image.png]


Date and Time:         8/29/2022 8:20:35 PM
Machine Name:          DESKTOP-L8EHEJ7
Operating System:      Microsoft Windows 10.0.17763 x64
Environment Version:   6.0.1
Genie Version:         4.0.2.4
Genie Build Date:      1/1/0001 12:00:00 AM

Main
File not found.

System.IO.FileNotFoundException: File not found.
   at Microsoft.VisualBasic._Interaction.Shell(String PathName, AppWinStyle
Style, Boolean Wait, Int32 Timeout)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1&
arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags
invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.VisualBasic.Interaction.InvokeMethod(String methodName,
Object[] args)
   at Microsoft.VisualBasic.Interaction.Shell(String PathName, AppWinStyle
Style, Boolean Wait, Int32 Timeout)
   at GenieClient.ScriptExplorer.ToolStripButtonEdit_Click(Object sender,
EventArgs e)
   at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons
button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg,
IntPtr wparam, IntPtr lparam)

*Orrin Cummins*
*オリン カミンス*

▌Japanese to English Translator
▌English Proofreader & Editor

▌Contact me to discuss the specifics of your project and find the
▌optimal solution to your Japanese to English translation needs.

***@***.***
