### ISSUE TITLE
Odd pushBold issue, the creature and the hide with same tap, are all highlighted

### ISSUE THREAD

**Issue by Thires** [GenieClient/Genie4#116]
This is with 4.0.2.4 and 4.0.2.405 (current pushes)
Also in 4.0.2.4 if you have a highlight (normal highlight) for creature it will be working
In 4.0.2.405 those highlights won't be

You can see that the "a lava drake" and "a lava drake hide" are being highlighted but not "some lava drake bones"

Room window picture

![unknown](https://user-images.githubusercontent.com/28072996/187374157-7725d4c5-8b36-4324-b665-b368ad5792ae.png)

Raw data

```You also see <pushBold/>a lava drake<popBold/>, some lava drake bones, <pushBold/>a lava drake<popBold/>, a lava drake hide, <pushBold/>a lava drake<<popBold/>, some lava drake bones, <pushBold/>a lava drake<popBold/>, some lava drake bones, a lava drake hide, some lava drake bones, some lava drake bones, a lava drake hide, some lava drake bones, a lava drake hide, some lava drake bones, some lava drake bones, a lava drake hide, some lava drake bones, some lava drake bones, a lava drake hide, some lava drake bones, some lava drake bones, a lava drake hide, some lava drake bones, a lava drake hide, a lava drake hide, a lava drake hide, a lava drake hide, some lava drake bones, some lava drake bones, some lava drake bones, some lava drake bones, some lava drake bones, some lava drake bones, some lava drake bones, a lava drake hide, some lava drake bones, a lava drake hide, some lava drake bones, some lava drake bones, some lava drake bones, some lava drake bones, a lava drake hide, a lava drake hide, some lava drake bones, some lava drake bones, some lava drake bones, a lava drake hide, a lava drake hide, a lava drake hide, a lava drake hide, some lava drake bones, some lava drake bones, a lava drake hide, some lava drake bones, a lava drake hide, a lava drake hide, some lava drake bones, a lava drake hide, some lava drake bones, some lava drake bones, some lava drake bones, some lava drake bones, a lava drake hide, some lava drake bones, some lava drake bones, a lava drake hide, some lava drake bones, a lava drake hide, some lava drake bones, a lava drake hide, some lava drake bones, some lava drake bones, some lava drake bones, a lava drake hide, a lava drake hide, a lava drake hide, a lava drake hide, a lava drake hide, a lava drake hide, a lava drake hide, some lava drake bones, a lava drake hide, a lava drake hide, some lava drake bones, some lava drake bones, a lava drake hide, some lava drake bones, some lava drake bones, some lava drake bones, some lava drake bones, a lava drake hide, some lava drake bones, some lava drake bones, a lava drake hide, some lava drake bones, a lava drake hide, some lava drake bones, some lava drake bones, some lava drake bones and some other stuff.```

**Comment by jingounchained** [comment]
Please try the latest test build at https://github.com/GenieClient/Genie4/releases/tag/Test_Build

I believe I have this resolved there. In the first iteration of the new method for highlighting presets and monsterbold items I matched Room Objects (the items that show in the "You also see" list of the room) using Regex, so what you're seeing is where it's matching things that aren't bolded.

**Comment by Thires** [comment]
Awesome, that fixed that
