### ISSUE TITLE
Inventory View plugin and deed register

### ISSUE THREAD

**Issue by hat071af** [GenieClient/Genie4#120]
It looks like the recent deed register updates broke the inventory view plug in. Using the scan inventory button doesn't advance to the home recall command after reading the register and the plugin no longer tracks items in the register.

My guess is that there was probably a change in the output of registers that the plugin isn't recognizing.

Currently using Genie v4.0.2.5 and Inventory View plugin v1.8

**Comment by mj-colonel-panic** [comment]
This is an issue for InventoryView - and I believe it's been addressed since this was opened.
