### ISSUE TITLE
Suggestion: Allow us to change the colors of the mana and concentration bars

### ISSUE THREAD

**Issue by MPLLC** [GenieClient/Genie4#156]
I've looked both in the wiki and in the configuration and I can't find any option to change the colors of the mana and concentration bars. White on aqua and white on white(!) are essentially unreadable, and shouldn't be default values

**Comment by digitalnyc1** [comment]
This is already configurable in 4.0.2.6.  In Configuration -> Highlights -> Presets.  You can change the health, mana, concentration, fatigue and spirit bar foreground and background colors.  Not sure if it's possible to change the overlay text color for those.  The colors can also be controlled using the #preset command, e.g. #preset spirit orange,black

**Comment by mj-colonel-panic** [comment]
![image](https://github.com/GenieClient/Genie4/assets/32217493/07cd9266-e020-4557-8196-054858de39c4)
I'll look at the defaults but the colors can be managed under your highlight presets. I'll also ask our wiki fairy to add this to the wiki :)
