### ISSUE TITLE
Doesn't work with the CreateFormWithJS.dll

### ISSUE THREAD

**Issue by Thyon2377** [GenieClient/Genie4#16]
Using ubercombat, geniehunter or any other script that uses javascript menus won't work with Genie4

**Comment by Thyon2377** [comment]
#link command in scripts isn't working either.

**Comment by jingounchained** [comment]
can you attach the dll

**Comment by jingounchained** [comment]
there's a built copy in the "Plugins.zip" on recent Releases that contains a version of this plugin which has been tested successfully on this version of Genie
