### ISSUE TITLE
Whip attacks not outputting monsterbold

### ISSUE THREAD

**Issue by hat071af** [GenieClient/Genie4#164]
Whip attacks have monsterbold tags in the raw feed, but they aren't being displayed in Genie. They do display in Wrayth.

![Screenshot 2023-12-18 185748](https://github.com/GenieClient/Genie4/assets/16874682/3d87d331-dc03-4336-8eb7-7311b61ffafe)

```
<roundTime value='1702954135'/>You whip your leather whip at a giant mechanical mouse.<pushBold/>  The leather whip lands a solid hit to a giant mechanical mouse's abdomen.
<popBold/>[You're winded, nimbly balanced and overwhelming opponent.]
Roundtime: 2 sec.
<prompt time="1702954133">R&gt;</prompt>
```

**Comment by mj-colonel-panic** [comment]
The linebreak during the push/pop broke it. I've got a fix ready for test I'm pushing in Test Build 614
If you would like to try it you can get it at https://github.com/GenieClient/Genie4/releases/tag/Test_Build
![image](https://github.com/GenieClient/Genie4/assets/32217493/2cb422ad-3d89-493b-a5f4-b48c195b7d97)
