### ISSUE TITLE
Org Access

### ISSUE THREAD

**Issue by vtcifer** [GenieClient/Genie4#170]
@monil2233 Hoping you're still around to review pings in github - If you could pop in to the genie discord there are some access concerns to the org that need to be discussed.

**Comment by monil2233** [comment]
I’m in the ocean this weekend

Monday good?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Derek Hoffmann ***@***.***>
Sent: Friday, June 21, 2024 4:14:10 PM
To: GenieClient/Genie4 ***@***.***>
Cc: Jason Harman ***@***.***>; Mention ***@***.***>
Subject: [GenieClient/Genie4] Org Access (Issue #170)


@monil2233<https://github.com/monil2233> Hoping you're still around to review pings in github - If you could pop in to the genie discord there are some access concerns to the org that need to be discussed.

**Comment by vtcifer** [comment]
Yeah, that's perfectly ok.  Hope it's for vacation!
