### ISSUE TITLE
Also here list not updating in the Room window on character login

### ISSUE THREAD

**Issue by Blackstarsapphire** [GenieClient/Genie4#171]
When a character enters the game the **Also here** list in the room window is not updating.  It requires someone to enter or exit the room via normal methods or a logout in the room.

**Comment by vtcifer** [comment]
Is this a genie bug or a game bug? Does genie actually receive the right xml? I'm guessing no but would be good to include the raw xml info when you see this.

**Comment by vtcifer** [comment]
I got around to testing this today, and it's a game bug, not a bug with genie.  The game doesn't send the needed XML for genie to update the room window:


Entering room on first Login:
```xml
<prompt time="[redacted]">&gt;</prompt>
Foo just arrived.
<pushStream id="logons"/> * Foo joins the adventure.
<popStream/><prompt time="[redacted]">&gt;</prompt>
```

Player entering room without login:
```xml
<prompt time="1723482327">R&gt;</prompt>
Bar came through a heavy door.
<component id='room players'>Also here: Bar and Foo.</component>
<prompt time="1723482330">R&gt;</prompt>
```

The xml tag missing from the game is "<component id='room players'>"  Bug it in game and maybe the GMs will fix.
