### ISSUE TITLE
#lc doesn't work for me.

### ISSUE THREAD

**Issue by Kaesken** [GenieClient/Genie4#29]
![image](https://user-images.githubusercontent.com/23766705/149885147-706e3aeb-2256-4813-9524-6c8fb4a8150e.png)

It doesn't try to bring up the CMD file.  I even went into the settings file to put in the lich configurations and all it does is disconnect me and not log into it.

**Comment by jingounchained** [comment]
I'm investigating a fix for this now. As discussed in Discord this looks likely, to me, to be due to the path having the two slashes.
