### ISSUE TITLE
Spell Duration Variable intermittently returning 0

### ISSUE THREAD

**Issue by mrfarnan** [GenieClient/Genie4#34]
Running this command over and over to see why i'm recasting spells sooner than I should.
It intermittently fails, not having the correct value stored.
echo $SpellTimer.MachinistsTouch.duration

[17:49] echo 37
[17:49] 
> 
[17:49] echo 0
[17:49] 37
[17:49] 
> 
[17:49] 0
[17:49] 
> 
[17:49] echo 36
[17:49] 36
[17:49]

**Comment by jingounchained** [comment]
this is a known issue with the SpellTimer plugin and not Genie - the reason it's been a hassle to fix is I've been unable to recreate it.

**Comment by jingounchained** [comment]
Good news! This is fixed in the latest SpellTimer update - grab a copy here: https://github.com/GenieClient/Plugin_SpellTimer
