### ISSUE TITLE
"You are connected to the game. Are you sure you want to close?" displaying when typing quit after connecting via Lich via #lc <profile>

### ISSUE THREAD

**Issue by SekmehtDR** [GenieClient/Genie4#41]

**Comment by SekmehtDR** [comment]
Genie doesn't appear to detect that I've issued the `QUIT` command and prompts with the dialog box "You are connected to the game. Are you sure you want to close?" upon exiting Genie. When selecting yes, Genie then closes.

![2022-01-24 23_59_06-DR_ Sekmeht  Not connected  - Genie 4 0 1 0](https://user-images.githubusercontent.com/50120656/150935567-88bce242-264e-4ced-823e-73fc8a8830f3.png)
.

**Comment by SekmehtDR** [comment]
Genie Client 4
Version 4.0.1.0
Build Date 1/1/0001 12:00:00 AM
GPL-3
genieclient.com

**Comment by SekmehtDR** [comment]
I connected again via Lich, waited for 2 mins or so, issued `quit` and genie closed as expected. It seems to happen after running for some time. I'll try to see what I can find that might trigger it. Thanks all.

**Comment by vtcifer** [comment]
I'd almost guess this seems like it might be a lich bug?  
If Genie and lich are still technically connected even though lich isn't connected to  DR anymore.

**Comment by Kiriawen** [comment]
it's an issue with Genie waiting for Lich to fully disconnect.  I've had it happen for ages.  usually just waiting a short period of time and you wont get the error.  If you've issued the quit command to the game and you see the game exit out it is safe to just exit.  At least I've never had an issue when doing so.

**Comment by Kaesken** [comment]
If you typed
```
,ka
```
And wait for all lich scripts to exit, you can quit Genie without getting that message.

**Comment by SekmehtDR** [comment]
Thanks guys, I'll test this today. Mostly wanted to report it incase something needs to be done in Genie to handle shutdown of lich  or something going on in the game instance differently. I'll try the ``,ka`` before quitting to see if it exits normally.

**Comment by SekmehtDR** [comment]
#exit doesn't work while this issue occurs. The icon bars are still all colorized so Genie for sure doesn't think it's disconnected. Kind of weird that #exit doesn't work right?

**Comment by SekmehtDR** [comment]
Ahah, I found a crash window in the background:

Date and Time:         1/27/2022 1:39:02 AM
Machine Name:          DESKTOP-LQT34IP
Operating System:      Microsoft Windows 10.0.22000 x64
Environment Version:   6.0.1
Genie Version:         4.0.1.0
Genie Build Date:      1/1/0001 12:00:00 AM

Plugin Name:           Tracker
Plugin Version         1.0.1
Plugin Action:         ParentClosing

Object reference not set to an instance of an object.

----------------------------------------------
System.NullReferenceException: Object reference not set to an instance of an object.
   at Tracker.TrackerPlugin.ParentClosing()
   at GenieClient.FormMain.WndProc(Message& m)

**Comment by SekmehtDR** [comment]
![2022-01-27 01_40_41-Genie has encountered a problem](https://user-images.githubusercontent.com/50120656/151332962-f52f64e3-9821-4167-aa11-1ca7a7a0ad4c.png)

**Comment by SekmehtDR** [comment]
Okay, so after clearing the error, #exit still didn't work. I executed #var connected 0, this put genie into a disconnected state and I was able to close normally.

**Comment by SekmehtDR** [comment]
I think this can be closed, sounds like there isn't really a good way to get Lich to properly tell Genie to exit.
