### ISSUE TITLE
Genie 4.0.1.0, Genie error after trying to clear arrival window

### ISSUE THREAD

**Issue by SekmehtDR** [GenieClient/Genie4#53]
Hello, I received the following error when I tried to right-click > clear my arrival window. Hope this is of some value.

Date and Time:         1/31/2022 10:39:38 AM
Machine Name:          DESKTOP-LQT34IP
Operating System:      Microsoft Windows 10.0.22000 x64
Environment Version:   6.0.1
Genie Version:         4.0.1.0
Genie Build Date:      1/1/0001 12:00:00 AM

VariableChanged
Collection was modified; enumeration operation may not execute.

System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.ArrayList.ArrayListEnumeratorSimple.MoveNext()
   at GenieClient.FormMain.TriggerVariableChanged(String sVariableName)
   at GenieClient.FormMain.ClassCommand_EventVariableChanged(String sVariable)

**Comment by jingounchained** [comment]
can you please test this with the latest build and let me know if it still occurs?

**Comment by SekmehtDR** [comment]
I'm on 4.0.3 and have not had this issue again! Thanks, I'll resubmit if I get it again.

**Comment by jingounchained** [comment]
Sounds good, thank you!
