### ISSUE TITLE
Defect:  Genie Crash for unset var reference eval

### ISSUE THREAD

**Issue by snmurphy95** [GenieClient/Genie4#62]
OS:  Win 10
Genie Version:  4.0.1.2

Reproduction steps:
* Use a script to perform an evalmath on an unset variable.  ie:  `evalmath nextRefreshAt $lastRefreshGametime + 86400` where $lastRefreshGametime has not been initialized or is initialized incorrectly with `if (!($lastRefreshGametime >0)) then put #var $lastRefreshGametime 0`

Crash result does not give debug info from script or into logs.  Immediately closes both the problem window and the application.  It's a dumb typo, but it's a dumb typo that doesn't crash genie3.

**Comment by jingounchained** [comment]
This has been fixed in the latest release. The error is now caught and printed as script debug information when it occurs.
