### ISSUE TITLE
Defect: Genie crash when modifying arrays in a script

### ISSUE THREAD

**Issue by snmurphy95** [GenieClient/Genie4#63]
OS:  Win 10
Environment Version: 6.0.1
Genie Version: 4.0.1.2

Error:
> EndUpdate
> Collection was modified; enumeration operation may not execute.
> System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
> at
> System.Collections.ArrayList.ArrayList.EnumeratorSimple.MoveNext()
> atGenieClient.FormMain.ParseTriggers(String sText, Boolean bBufferWait)

Occurs when a local variable array such as `var skills Skill One|Skill Two|Skill Three|Skill Four` is resorted by building a second array and iterating through the first.

**Comment by jingounchained** [comment]
can you please test this with the latest build and let me know if it still occurs?

**Comment by snmurphy95** [comment]
Sure, I'll set up and give it a run.

**Comment by snmurphy95** [comment]
Four hours in and it has not reoccurred with the same scripts.  Good to call this one resolved!

**Comment by jingounchained** [comment]
Wonderful! Thank you for confirming!

**Comment by jingounchained** [comment]
doh you closed...lol closing again
