### ISSUE TITLE
Layout shifts down when script starts causing scroll bars to appear

### ISSUE THREAD

**Issue by DamianDRX** [GenieClient/Genie4#68]
![No Script Layout](https://user-images.githubusercontent.com/101422329/157923789-866d917f-0d25-4fca-a287-38503b4bf350.jpg)
![Script Active Layout](https://user-images.githubusercontent.com/101422329/157923800-8978125a-070b-41bc-8a09-bc3ba02c57b6.jpg)

Attached pictures show the issue, when the script name pops up on the screen, it does not fit in the area designated for it and pushes the windows below it down. If those windows are as tall as they can be, they are pushed outside the area of the window and it causes the scroll bars to become visible until the script is done running at which point the scroll bars disappear. This was not an issue with the previous Genie 3 version.

**Comment by jingounchained** [comment]
I'm not seeing the difference between these two screenshots. What is the before state? Sorry, can you circle what changed? Trying to understand.

**Comment by DamianDRX** [comment]
Apologies for not being more clear, here are the same screen shots with the circled areas that change from the state where a script is not running to a state when the script is active.

![No Script Layout](https://user-images.githubusercontent.com/101422329/158218123-8fdca93f-fcd9-41f0-b272-c8b632697e71.jpg)
![Script Active Layout](https://user-images.githubusercontent.com/101422329/158218128-3236f7e1-0882-4614-99fa-6ec420f2795b.jpg)

**Comment by DamianDRX** [comment]
It seems like when the script name populates in the top left corner of the screen, it creates a graphic larger (vertically) than the space allotted for it to actually take up and therefore pushes everything down just a hair, enough to cause scroll bars to pop up. Hopefully that's more clear.

**Comment by jingounchained** [comment]
Ah I totally overlooked that somehow and stared at both for like 5 minutes trying to figure it out lol sorry

This is the only time I've seen this happen - for most people the bar is big enough. Do you have the script bar unchecked under layout? Not sure that would be it though either.
![image](https://user-images.githubusercontent.com/32217493/158224195-38e9393d-96af-44e2-9118-82c117d51bcc.png)

**Comment by DamianDRX** [comment]
Nope, just checked, the script bar is indeed checked.

**Comment by Kaedan810** [comment]
Hi - this is still happening in 4.0.2.3.  I'm running Genie in Parallels.  For some reason, the actual text windows are expanded into the border area - if you look at where it says "game" on the main window, you'll see it's half cut off.  Same with all other windows.  Wondering if this has anything to do with it.
<img width="1488" alt="Screen Shot 2022-03-28 at 10 01 11 AM" src="https://user-images.githubusercontent.com/70026046/160427918-535a2588-8766-474a-84af-5bbcd4a83a2f.png">

Thanks for all your hard work on this!

**Comment by LaegotKit** [comment]
The fix for this is to run a script, pause it, and re-snap the windows to the client window and re-save your layout. Re-snap by slowly dragging the title bar of each of the windows along the bottom edge up until you see it jump up about one pixel.

![image](https://user-images.githubusercontent.com/100539902/171967572-f9d7cf40-5e63-46d7-84c0-81aa7d5b55d1.png)

![image](https://user-images.githubusercontent.com/100539902/171967595-4ac18291-3dee-4f56-a3a7-f72f52c81a46.png)

![image](https://user-images.githubusercontent.com/100539902/171967629-fc2bc82f-f6f3-481e-a2f0-154c3c602032.png)

**Comment by jingounchained** [comment]
@LaegotKit 's steps above resolve this issue. Closing.
