### ISSUE TITLE
Break/Fix: Maps are unable to fully scroll up and down.

### ISSUE THREAD

**Issue by Terramotus** [GenieClient/Genie4#8]
Unable to scroll up and down through the entire map on several map on Genie 4, running 1920x1080.  Crossing and Boar Clan are two good examples of this.  Left and right scrolling works fully to traverse the entire map, but the top half is cut off of the scrollbar.

**Comment by jingounchained** [comment]
GetOffset() in NodeList is a starting point for identifying the problem. 
The map is scrollable but the problem appears to be in the positioning either of the map .on the panel it's drawn on, or the position of that panel in the form's scrollable viewport.
