### ISSUE TITLE
Suggestion: Allow sorting of triggers/subs/gags/etc by class/regex/action

### ISSUE THREAD

**Issue by DamianDRX** [GenieClient/Genie4#95]
Currently you can click on the word "eval" or "class" when you look at triggers for example but they do absolutely nothing and it would be highly helpful if i could use these column headers to sort, for example, all triggers under a certain class rather than having to wade through and find all triggers with the class "cornmaze" etc. Ideally, this sort would survive clicking OK and reopening the Configuration window too. See attached.
![Sample](https://user-images.githubusercontent.com/101422329/163044723-e7c9ad9b-2859-4e90-83ac-bf96f110e70b.png)

**Comment by dantiadr** [comment]
Closing this as it's already been submitted in #5
